Submerged Common fix
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #1261
Opened 2024-06-24 08:04 UTC by Thunderblade73

![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/assets/85900443/7e9b1741-17be-4505-8eee-f06313788540)
Wiki disagrees with the common rarity of submerged. The wiki says it has 1 Fishing Speed but in the file it misses that stat.

Ehm, also fandom is wrong. I guess.
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/assets/85900443/269b09fd-171a-449c-8218-55c5948222c6)

Real Item
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/assets/85900443/00186e56-74f5-4623-8378-f4ffc919feb8)

2024-06-24 08:13 UTC, NopoTheGamer commented
how do you know it isnt the hypixel wiki that's wrong

2024-06-24 08:20 UTC, Thunderblade73 commented
> how do you know it isnt the hypixel wiki that's wrong

I checked for you ingame now.
![image](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/assets/85900443/33e3c0fc-88f3-44ed-a947-79813f669fcf)

2024-06-24 08:22 UTC, NopoTheGamer submitted a review, later dismissed

2024-06-25 21:06 UTC, jani270 requested changes
Wrong Branch

2024-06-28 17:28 UTC, jani270 approved these changes

2024-07-01 20:44 UTC, merged