update fishing pets
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #1543
Opened 2024-12-21 08:41 UTC by catgirlseraid

ammonite
yeti
blue whale
dolphin
flying fish
megalodon
reindeer
squid

2024-12-21 14:09 UTC, jani270 requested changes
![grafik](https://github.com/user-attachments/assets/abae3da7-69c0-499c-afc1-24c1403be2e2)
lmao (account doesnt have hotm unlocked)*

2024-12-21 23:58 UTC, catgirlseraid commented
changed ammonite from +0.05% -> +0.06% and +5% -> +6%

2024-12-22 00:07 UTC, jani270 commented on constants/petnums.json
> +        "otherNums":  [
Whats up with this?

2024-12-22 00:18 UTC, jani270 approved these changes
surely this is all fine

2024-12-22 00:19 UTC, merged