Looting IV rarity fix
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #656
Opened 2021-11-14 17:52 UTC by 32Vache

Rarity of Looting IV book is Uncommon and not Rare

2021-11-14 17:58 UTC, jani270 requested changes
Hi, the tier of looting IV got changed to common not uncommon. Please fix that and we can merge it.
![image](https://user-images.githubusercontent.com/69345714/141692650-77ddf65f-29e3-445e-a3a2-52c597f0ee1d.png)

2021-11-14 21:05 UTC, 32Vache commented
Corrected it

2021-11-15 02:51 UTC, IRONM00N approved these changes

2021-11-15 09:05 UTC, jani270 approved these changes

2021-11-15 09:06 UTC, merged