add new patron info
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #685
Opened 2022-01-29 17:39 UTC by koxx12-dev-is-bad

* Update misc.json

2022-01-30 13:19 UTC, DeDiamondPro submitted a review, later dismissed
looks good to me

2022-02-01 10:05 UTC, jani270 requested changes

2022-02-01 10:05 UTC, jani270 commented on constants/misc.json
> +      "§7If you still wish to support him §c§l with no reward§r§7 his §6§lPatreon§r§7 is:",
```suggestion
      "§7If you still wish to support him §c§lwith no reward§r§7 his §6§lPatreon§r§7 is:",
```

2022-02-01 20:32 UTC, koxx12-dev-is-bad commented
fixed 👍

2022-02-01 20:57 UTC, jani270 approved these changes

2022-02-03 15:37 UTC, DeDiamondPro approved these changes

2022-02-03 15:40 UTC, merged