Hypixeling
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #745
Opened 2022-05-25 17:07 UTC by Lulonaut

Flaming fist can no longer be crafted

Burststopper artifact now requires the talisman to be crafted

2022-05-25 21:13 UTC, NopoTheGamer submitted a review, later dismissed

2022-05-25 23:37 UTC, jani270 requested changes
Burststopper Artifact is still wrong, the compact ooze should be whipped magma cream

2022-05-26 09:03 UTC, NopoTheGamer approved these changes

2022-05-26 19:42 UTC, jani270 approved these changes

2022-05-26 19:42 UTC, merged