Add misc items
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #765
Opened 2022-06-12 12:20 UTC by cyoung06

(Please, thank you)

2022-06-12 12:21 UTC, cyoung06 commented
Flowers also have other plants

2022-06-12 12:21 UTC, jani270 requested changes
All of them are missing the   "vanilla": true, tag

2022-06-12 17:54 UTC, jani270 approved these changes

2022-06-12 22:06 UTC, cyoung06 commented
@NopoTheGamer hi can you please review this (tysm)

2022-06-13 01:36 UTC, NopoTheGamer approved these changes

2022-06-13 01:36 UTC, merged