Added new enchants to maxed enchant book
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #797
Opened 2022-08-10 20:52 UTC by SchIaumeyer

2022-08-10 20:54 UTC, jani270 requested changes

2022-08-10 20:54 UTC, jani270 commented on items/MAXED_ENCHANT_BOOK.json
> +    "§9Venomous VI§9, §9Vicious V§9,",
Please revert that change.

2022-08-10 21:08 UTC, SchIaumeyer commented on items/MAXED_ENCHANT_BOOK.json
> +    "§9Venomous VI§9, §9Vicious V§9,",
ohh i fd up

2022-08-11 07:44 UTC, jani270 reviewed
Seems technically fine but could you maybe also add the other 2 enchants from the chili pepper collection? (Tabasco & Habanero Tactics)

2022-08-11 07:56 UTC, SchIaumeyer commented
If you could rely on the official wiki for once...

2022-08-11 08:19 UTC, jani270 approved these changes

2022-08-11 08:20 UTC, NopoTheGamer approved these changes

2022-08-11 08:20 UTC, merged