Remove common and uncommon Scatha.
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #845
Opened 2022-10-15 15:12 UTC by Irian3x3

2022-10-17 08:27 UTC, jani270 requested changes
You removed the petnums but not the pets. Please also remove the pets itself

2022-10-17 20:22 UTC, Irian3x3 commented
> You removed the petnums but not the pets. Please also remove the pets itself

Fixed.

2022-10-21 07:27 UTC, jani270 submitted a review, later dismissed

2022-10-29 10:13 UTC, NopoTheGamer approved these changes

2022-10-29 10:18 UTC, jani270 approved these changes

2022-10-29 10:18 UTC, merged