Update UDEL_NPC.json
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #847
Opened 2022-10-19 11:06 UTC by ENORMOUZ

2022-10-19 11:16 UTC, ENORMOUZ commented
funny how its called Archeologist in bestiary but Archaeologist in wikis

2022-10-19 12:03 UTC, ENORMOUZ commented
Remind me to add Byzantium Dye to Voidling drop table

2022-10-19 12:51 UTC, ENORMOUZ commented
Nvm it only drops from minion spawned voidlings and not the guys in end (i think)

2022-10-19 13:04 UTC, jani270 requested changes

2022-10-19 13:04 UTC, jani270 commented on items/NECRON_BOSS.json
> -          "id": "",
Fixed in another pr

2022-10-19 13:04 UTC, ENORMOUZ commented on items/NECRON_BOSS.json
> -          "id": "",
how do i unfix my version or smth

2022-10-19 13:09 UTC, jani270 commented on items/NECRON_BOSS.json
> -          "id": "",
Revert your commit?

2022-10-20 06:11 UTC, ENORMOUZ commented
Should this pr be merged into my other one? Also is there even a way to do so lol

2022-10-20 06:41 UTC, jani270 commented
> Should this pr be merged into my other one? Also is there even a way to do so lol

For god sake no, the other pr is already a mess with the most useless changes in gods existence. We dont need more shit in there

2022-10-21 07:28 UTC, jani270 approved these changes

2022-10-21 16:47 UTC, Lulonaut approved these changes

2022-10-21 16:47 UTC, merged