some raffle stuff and other stuff
NotEnoughUpdates/NotEnoughUpdates-REPO pull request #975
Opened 2023-09-04 10:00 UTC by CalMWolfs

2023-09-04 10:26 UTC, jani270 requested changes
Items are already in my pr :)

2023-09-04 10:26 UTC, jani270 commented on constants/misc.json
> +    "eaa5623c841346b7a74b2d74a42b2841"
No more rainbow names

2023-09-04 10:28 UTC, Ascynx commented on constants/misc.json
> +    "eaa5623c841346b7a74b2d74a42b2841"
so sad

2023-09-05 13:28 UTC, jani270 approved these changes

2023-09-06 14:21 UTC, Lulonaut approved these changes

2023-09-06 14:21 UTC, merged